sudo: false
language: node_js
node_js: stable
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      name: "Lint JS"
      script: npm run lint:js
    - script: npm run lint:ec
      name: "Lint by editorconfig"
    - stage: test
      name: "Unit tests"
      after_success: npm run coverage
